package com.ns.common.model;

import com.ns.common.model.base.BaseBasCustRelation;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BasCustRelation extends BaseBasCustRelation<BasCustRelation> {
	public static final BasCustRelation dao = new BasCustRelation().dao();
}
