package com.ns.common.model;

import com.ns.common.model.base.BaseBasCustomerExt;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BasCustomerExt extends BaseBasCustomerExt<BasCustomerExt> {
	public static final BasCustomerExt dao = new BasCustomerExt().dao();
}
