package com.ns.common.model;

import com.ns.common.model.base.BaseBasCustQrcode;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BasCustQrcode extends BaseBasCustQrcode<BasCustQrcode> {
	public static final BasCustQrcode dao = new BasCustQrcode().dao();
}
