package com.ns.common.model;

import com.ns.common.model.base.BaseBasCustLike;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BasCustLike extends BaseBasCustLike<BasCustLike> {
	public static final BasCustLike dao = new BasCustLike().dao();
}
