package com.ns.common.model;

import com.ns.common.model.base.BaseBasCustPointTrans;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BasCustPointTrans extends BaseBasCustPointTrans<BasCustPointTrans> {
	public static final BasCustPointTrans dao = new BasCustPointTrans().dao();
}
