package com.ns.common.model;

import com.ns.common.model.base.BaseBasCustAddress;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BasCustAddress extends BaseBasCustAddress<BasCustAddress> {
	public static final BasCustAddress dao = new BasCustAddress().dao();
}
