package com.ns.common.model;

import com.ns.common.model.base.BaseBasCustomerRequest;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BasCustomerRequest extends BaseBasCustomerRequest<BasCustomerRequest> {
	public static final BasCustomerRequest dao = new BasCustomerRequest().dao();
}
