package com.ns.common.model;

import com.ns.common.model.base.BaseBasCustomer;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BasCustomer extends BaseBasCustomer<BasCustomer> {
	public static final BasCustomer dao = new BasCustomer().dao();
}
