package com.ns.common.model;

import com.ns.common.model.base.BaseBasCustPoints;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BasCustPoints extends BaseBasCustPoints<BasCustPoints> {
	public static final BasCustPoints dao = new BasCustPoints().dao();
}
