package com.ns.common.model;

import com.ns.common.model.base.BaseNodeContent;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class NodeContent extends BaseNodeContent<NodeContent> {
	public static final NodeContent dao = new NodeContent().dao();
}
