package com.ns.common.model;

import com.ns.common.model.base.BaseNodeCollection;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class NodeCollection extends BaseNodeCollection<NodeCollection> {
	public static final NodeCollection dao = new NodeCollection().dao();
}
