package com.ns.common.model;

import com.ns.common.model.base.BaseNodeCategory;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class NodeCategory extends BaseNodeCategory<NodeCategory> {
	public static final NodeCategory dao = new NodeCategory().dao();
}
