package com.ns.common.model;

import com.ns.common.model.base.BaseNodeLike;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class NodeLike extends BaseNodeLike<NodeLike> {
	public static final NodeLike dao = new NodeLike().dao();
}
