package com.ns.common.model;

import com.ns.common.model.base.BaseNodeFocus;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class NodeFocus extends BaseNodeFocus<NodeFocus> {
	public static final NodeFocus dao = new NodeFocus().dao();
}
