package com.ns.common.model;

import com.ns.common.model.base.BaseNodeCmt;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class NodeCmt extends BaseNodeCmt<NodeCmt> {
	public static final NodeCmt dao = new NodeCmt().dao();
}
