package com.ns.common.model;

import com.ns.common.model.base.BasePntCategories;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PntCategories extends BasePntCategories<PntCategories> {
	public static final PntCategories dao = new PntCategories().dao();
}
