package com.ns.common.model;

import com.ns.common.model.base.BasePntMenu;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PntMenu extends BasePntMenu<PntMenu> {
	public static final PntMenu dao = new PntMenu().dao();
}
