package com.ns.common.model;

import com.ns.common.model.base.BasePntProduct;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PntProduct extends BasePntProduct<PntProduct> {
	public static final PntProduct dao = new PntProduct().dao();
}
