package com.ns.common.model;

import com.ns.common.model.base.BasePntProductCmt;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PntProductCmt extends BasePntProductCmt<PntProductCmt> {
	public static final PntProductCmt dao = new PntProductCmt().dao();
}
