package com.ns.common.model;

import com.ns.common.model.base.BasePntSku;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PntSku extends BasePntSku<PntSku> {
	public static final PntSku dao = new PntSku().dao();
}
