package com.ns.common.model;

import com.ns.common.model.base.BaseTldCoupon;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TldCoupon extends BaseTldCoupon<TldCoupon> {
	public static final TldCoupon dao = new TldCoupon().dao();
}
