package com.ns.common.model;

import com.ns.common.model.base.BaseTldCouponGrant;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TldCouponGrant extends BaseTldCouponGrant<TldCouponGrant> {
	public static final TldCouponGrant dao = new TldCouponGrant().dao();
}
