package com.ns.common.model;

import com.ns.common.model.base.BaseTldIdentifyCode;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TldIdentifyCode extends BaseTldIdentifyCode<TldIdentifyCode> {
	public static final TldIdentifyCode dao = new TldIdentifyCode().dao();
}
