package com.ns.common.model;

import com.ns.common.model.base.BaseTldOrderSplit;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TldOrderSplit extends BaseTldOrderSplit<TldOrderSplit> {
	public static final TldOrderSplit dao = new TldOrderSplit().dao();
}
