package com.ns.common.model;

import com.ns.common.model.base.BaseTldOrderItems;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TldOrderItems extends BaseTldOrderItems<TldOrderItems> {
	public static final TldOrderItems dao = new TldOrderItems().dao();
}
