package com.ns.common.model;

import com.ns.common.model.base.BaseTldOrders;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TldOrders extends BaseTldOrders<TldOrders> {
	public static final TldOrders dao = new TldOrders().dao();
}
