package com.ns.common.model;

import com.ns.common.model.base.BaseTldPhotos;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TldPhotos extends BaseTldPhotos<TldPhotos> {
	public static final TldPhotos dao = new TldPhotos().dao();
}
