package com.ns.common.model;

import com.ns.common.model.base.BaseTldQrbgmParams;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TldQrbgmParams extends BaseTldQrbgmParams<TldQrbgmParams> {
	public static final TldQrbgmParams dao = new TldQrbgmParams().dao();
}
