package com.ns.common.model;

import com.ns.common.model.base.BaseTldSiteMsg;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TldSiteMsg extends BaseTldSiteMsg<TldSiteMsg> {
	public static final TldSiteMsg dao = new TldSiteMsg().dao();
}
