package com.ns.common.model;

import com.ns.common.model.base.BaseTreenodes;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Treenodes extends BaseTreenodes<Treenodes> {
	public static final Treenodes dao = new Treenodes().dao();
}
