package com.ns.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseBasCustRelation<M extends BaseBasCustRelation<M>> extends Model<M> implements IBean {

	public M setID(java.lang.String ID) {
		set("ID", ID);
		return (M)this;
	}
	
	public java.lang.String getID() {
		return getStr("ID");
	}

	public M setRpNo(java.lang.String rpNo) {
		set("RP_NO", rpNo);
		return (M)this;
	}
	
	public java.lang.String getRpNo() {
		return getStr("RP_NO");
	}

	public M setOpenId(java.lang.String openId) {
		set("OPEN_ID", openId);
		return (M)this;
	}
	
	public java.lang.String getOpenId() {
		return getStr("OPEN_ID");
	}

	public M setNickName(java.lang.String nickName) {
		set("NICK_NAME", nickName);
		return (M)this;
	}
	
	public java.lang.String getNickName() {
		return getStr("NICK_NAME");
	}

	public M setSEX(java.lang.Integer SEX) {
		set("SEX", SEX);
		return (M)this;
	}
	
	public java.lang.Integer getSEX() {
		return getInt("SEX");
	}

	public M setCOUNTRY(java.lang.String COUNTRY) {
		set("COUNTRY", COUNTRY);
		return (M)this;
	}
	
	public java.lang.String getCOUNTRY() {
		return getStr("COUNTRY");
	}

	public M setPROVINCE(java.lang.String PROVINCE) {
		set("PROVINCE", PROVINCE);
		return (M)this;
	}
	
	public java.lang.String getPROVINCE() {
		return getStr("PROVINCE");
	}

	public M setCITY(java.lang.String CITY) {
		set("CITY", CITY);
		return (M)this;
	}
	
	public java.lang.String getCITY() {
		return getStr("CITY");
	}

	public M setPIC(java.lang.String PIC) {
		set("PIC", PIC);
		return (M)this;
	}
	
	public java.lang.String getPIC() {
		return getStr("PIC");
	}

	public M setENABLED(java.lang.Integer ENABLED) {
		set("ENABLED", ENABLED);
		return (M)this;
	}
	
	public java.lang.Integer getENABLED() {
		return getInt("ENABLED");
	}

	public M setVERSION(java.lang.Integer VERSION) {
		set("VERSION", VERSION);
		return (M)this;
	}
	
	public java.lang.Integer getVERSION() {
		return getInt("VERSION");
	}

	public M setSTATUS(java.lang.Integer STATUS) {
		set("STATUS", STATUS);
		return (M)this;
	}
	
	public java.lang.Integer getSTATUS() {
		return getInt("STATUS");
	}

	public M setREMARK(java.lang.String REMARK) {
		set("REMARK", REMARK);
		return (M)this;
	}
	
	public java.lang.String getREMARK() {
		return getStr("REMARK");
	}

	public M setCreateBy(java.lang.String createBy) {
		set("CREATE_BY", createBy);
		return (M)this;
	}
	
	public java.lang.String getCreateBy() {
		return getStr("CREATE_BY");
	}

	public M setCreateDt(java.lang.String createDt) {
		set("CREATE_DT", createDt);
		return (M)this;
	}
	
	public java.lang.String getCreateDt() {
		return getStr("CREATE_DT");
	}

	public M setUpdateDt(java.lang.String updateDt) {
		set("UPDATE_DT", updateDt);
		return (M)this;
	}
	
	public java.lang.String getUpdateDt() {
		return getStr("UPDATE_DT");
	}

}
