package com.ns.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BasePntProduct<M extends BasePntProduct<M>> extends Model<M> implements IBean {

	public M setID(java.lang.String ID) {
		set("ID", ID);
		return (M)this;
	}
	
	public java.lang.String getID() {
		return getStr("ID");
	}

	public M setProductName(java.lang.String productName) {
		set("PRODUCT_NAME", productName);
		return (M)this;
	}
	
	public java.lang.String getProductName() {
		return getStr("PRODUCT_NAME");
	}

	public M setPyCode(java.lang.String pyCode) {
		set("PY_CODE", pyCode);
		return (M)this;
	}
	
	public java.lang.String getPyCode() {
		return getStr("PY_CODE");
	}

	public M setProductCode(java.lang.String productCode) {
		set("PRODUCT_CODE", productCode);
		return (M)this;
	}
	
	public java.lang.String getProductCode() {
		return getStr("PRODUCT_CODE");
	}

	public M setCATEGORY(java.lang.String CATEGORY) {
		set("CATEGORY", CATEGORY);
		return (M)this;
	}
	
	public java.lang.String getCATEGORY() {
		return getStr("CATEGORY");
	}

	public M setBrandId(java.lang.String brandId) {
		set("BRAND_ID", brandId);
		return (M)this;
	}
	
	public java.lang.String getBrandId() {
		return getStr("BRAND_ID");
	}

	public M setAbbName(java.lang.String abbName) {
		set("ABB_NAME", abbName);
		return (M)this;
	}
	
	public java.lang.String getAbbName() {
		return getStr("ABB_NAME");
	}

	public M setSalPrice(java.math.BigDecimal salPrice) {
		set("SAL_PRICE", salPrice);
		return (M)this;
	}
	
	public java.math.BigDecimal getSalPrice() {
		return get("SAL_PRICE");
	}

	public M setSTOCK(java.lang.Integer STOCK) {
		set("STOCK", STOCK);
		return (M)this;
	}
	
	public java.lang.Integer getSTOCK() {
		return getInt("STOCK");
	}

	public M setTITLE(java.lang.String TITLE) {
		set("TITLE", TITLE);
		return (M)this;
	}
	
	public java.lang.String getTITLE() {
		return getStr("TITLE");
	}

	public M setImageUrl(java.lang.String imageUrl) {
		set("IMAGE_URL", imageUrl);
		return (M)this;
	}
	
	public java.lang.String getImageUrl() {
		return getStr("IMAGE_URL");
	}

	public M setThumbUrl(java.lang.String thumbUrl) {
		set("THUMB_URL", thumbUrl);
		return (M)this;
	}
	
	public java.lang.String getThumbUrl() {
		return getStr("THUMB_URL");
	}

	public M setBriefDescription(java.lang.String briefDescription) {
		set("BRIEF_DESCRIPTION", briefDescription);
		return (M)this;
	}
	
	public java.lang.String getBriefDescription() {
		return getStr("BRIEF_DESCRIPTION");
	}

	public M setIntegralTag(java.lang.Integer integralTag) {
		set("INTEGRAL_TAG", integralTag);
		return (M)this;
	}
	
	public java.lang.Integer getIntegralTag() {
		return getInt("INTEGRAL_TAG");
	}

	public M setIntegralSelf(java.lang.Integer integralSelf) {
		set("INTEGRAL_SELF", integralSelf);
		return (M)this;
	}
	
	public java.lang.Integer getIntegralSelf() {
		return getInt("INTEGRAL_SELF");
	}

	public M setIntegralSup(java.lang.Integer integralSup) {
		set("INTEGRAL_SUP", integralSup);
		return (M)this;
	}
	
	public java.lang.Integer getIntegralSup() {
		return getInt("INTEGRAL_SUP");
	}

	public M setDisplaySeq(java.lang.Integer displaySeq) {
		set("DISPLAY_SEQ", displaySeq);
		return (M)this;
	}
	
	public java.lang.Integer getDisplaySeq() {
		return getInt("DISPLAY_SEQ");
	}

	public M setENABLED(java.lang.Integer ENABLED) {
		set("ENABLED", ENABLED);
		return (M)this;
	}
	
	public java.lang.Integer getENABLED() {
		return getInt("ENABLED");
	}

	public M setVERSION(java.lang.Integer VERSION) {
		set("VERSION", VERSION);
		return (M)this;
	}
	
	public java.lang.Integer getVERSION() {
		return getInt("VERSION");
	}

	public M setSTATUS(java.lang.Integer STATUS) {
		set("STATUS", STATUS);
		return (M)this;
	}
	
	public java.lang.Integer getSTATUS() {
		return getInt("STATUS");
	}

	public M setREMARK(java.lang.String REMARK) {
		set("REMARK", REMARK);
		return (M)this;
	}
	
	public java.lang.String getREMARK() {
		return getStr("REMARK");
	}

	public M setCreateBy(java.lang.String createBy) {
		set("CREATE_BY", createBy);
		return (M)this;
	}
	
	public java.lang.String getCreateBy() {
		return getStr("CREATE_BY");
	}

	public M setCreateDt(java.lang.String createDt) {
		set("CREATE_DT", createDt);
		return (M)this;
	}
	
	public java.lang.String getCreateDt() {
		return getStr("CREATE_DT");
	}

	public M setUpdateDt(java.lang.String updateDt) {
		set("UPDATE_DT", updateDt);
		return (M)this;
	}
	
	public java.lang.String getUpdateDt() {
		return getStr("UPDATE_DT");
	}

}
