package com.ns.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTldPhotos<M extends BaseTldPhotos<M>> extends Model<M> implements IBean {

	public M setID(java.lang.String ID) {
		set("ID", ID);
		return (M)this;
	}
	
	public java.lang.String getID() {
		return getStr("ID");
	}

	public M setRelationId(java.lang.String relationId) {
		set("RELATION_ID", relationId);
		return (M)this;
	}
	
	public java.lang.String getRelationId() {
		return getStr("RELATION_ID");
	}

	public M setSysId(java.lang.Integer sysId) {
		set("SYS_ID", sysId);
		return (M)this;
	}
	
	public java.lang.Integer getSysId() {
		return getInt("SYS_ID");
	}

	public M setTYPE(java.lang.Integer TYPE) {
		set("TYPE", TYPE);
		return (M)this;
	}
	
	public java.lang.Integer getTYPE() {
		return getInt("TYPE");
	}

	public M setURL(java.lang.String URL) {
		set("URL", URL);
		return (M)this;
	}
	
	public java.lang.String getURL() {
		return getStr("URL");
	}

	public M setHrefUrl(java.lang.String hrefUrl) {
		set("HREF_URL", hrefUrl);
		return (M)this;
	}
	
	public java.lang.String getHrefUrl() {
		return getStr("HREF_URL");
	}

	public M setDisplaySeq(java.lang.Integer displaySeq) {
		set("DISPLAY_SEQ", displaySeq);
		return (M)this;
	}
	
	public java.lang.Integer getDisplaySeq() {
		return getInt("DISPLAY_SEQ");
	}

	public M setENABLED(java.lang.Integer ENABLED) {
		set("ENABLED", ENABLED);
		return (M)this;
	}
	
	public java.lang.Integer getENABLED() {
		return getInt("ENABLED");
	}

	public M setVERSION(java.lang.Integer VERSION) {
		set("VERSION", VERSION);
		return (M)this;
	}
	
	public java.lang.Integer getVERSION() {
		return getInt("VERSION");
	}

	public M setSTATUS(java.lang.Integer STATUS) {
		set("STATUS", STATUS);
		return (M)this;
	}
	
	public java.lang.Integer getSTATUS() {
		return getInt("STATUS");
	}

	public M setREMARK(java.lang.String REMARK) {
		set("REMARK", REMARK);
		return (M)this;
	}
	
	public java.lang.String getREMARK() {
		return getStr("REMARK");
	}

	public M setCreateBy(java.lang.String createBy) {
		set("CREATE_BY", createBy);
		return (M)this;
	}
	
	public java.lang.String getCreateBy() {
		return getStr("CREATE_BY");
	}

	public M setCreateDt(java.lang.String createDt) {
		set("CREATE_DT", createDt);
		return (M)this;
	}
	
	public java.lang.String getCreateDt() {
		return getStr("CREATE_DT");
	}

	public M setUpdateDt(java.lang.String updateDt) {
		set("UPDATE_DT", updateDt);
		return (M)this;
	}
	
	public java.lang.String getUpdateDt() {
		return getStr("UPDATE_DT");
	}

}
