package com.ns.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BasePntSku<M extends BasePntSku<M>> extends Model<M> implements IBean {

	public M setID(java.lang.String ID) {
		set("ID", ID);
		return (M)this;
	}
	
	public java.lang.String getID() {
		return getStr("ID");
	}

	public M setProductId(java.lang.String productId) {
		set("PRODUCT_ID", productId);
		return (M)this;
	}
	
	public java.lang.String getProductId() {
		return getStr("PRODUCT_ID");
	}

	public M setSKU(java.lang.String SKU) {
		set("SKU", SKU);
		return (M)this;
	}
	
	public java.lang.String getSKU() {
		return getStr("SKU");
	}

	public M setSalPrice(java.math.BigDecimal salPrice) {
		set("SAL_PRICE", salPrice);
		return (M)this;
	}
	
	public java.math.BigDecimal getSalPrice() {
		return get("SAL_PRICE");
	}

	public M setSTOCK(java.lang.Integer STOCK) {
		set("STOCK", STOCK);
		return (M)this;
	}
	
	public java.lang.Integer getSTOCK() {
		return getInt("STOCK");
	}

	public M setImageUrl(java.lang.String imageUrl) {
		set("IMAGE_URL", imageUrl);
		return (M)this;
	}
	
	public java.lang.String getImageUrl() {
		return getStr("IMAGE_URL");
	}

	public M setThumbUrl(java.lang.String thumbUrl) {
		set("THUMB_URL", thumbUrl);
		return (M)this;
	}
	
	public java.lang.String getThumbUrl() {
		return getStr("THUMB_URL");
	}

	public M setBriefDescription(java.lang.String briefDescription) {
		set("BRIEF_DESCRIPTION", briefDescription);
		return (M)this;
	}
	
	public java.lang.String getBriefDescription() {
		return getStr("BRIEF_DESCRIPTION");
	}

	public M setSelDefault(java.lang.Integer selDefault) {
		set("SEL_DEFAULT", selDefault);
		return (M)this;
	}
	
	public java.lang.Integer getSelDefault() {
		return getInt("SEL_DEFAULT");
	}

	public M setIntegralTag(java.lang.Integer integralTag) {
		set("INTEGRAL_TAG", integralTag);
		return (M)this;
	}
	
	public java.lang.Integer getIntegralTag() {
		return getInt("INTEGRAL_TAG");
	}

	public M setIntegralSelf(java.lang.Integer integralSelf) {
		set("INTEGRAL_SELF", integralSelf);
		return (M)this;
	}
	
	public java.lang.Integer getIntegralSelf() {
		return getInt("INTEGRAL_SELF");
	}

	public M setIntegralSup(java.lang.Integer integralSup) {
		set("INTEGRAL_SUP", integralSup);
		return (M)this;
	}
	
	public java.lang.Integer getIntegralSup() {
		return getInt("INTEGRAL_SUP");
	}

	public M setWEIGHT(java.math.BigDecimal WEIGHT) {
		set("WEIGHT", WEIGHT);
		return (M)this;
	}
	
	public java.math.BigDecimal getWEIGHT() {
		return get("WEIGHT");
	}

	public M setUNIT(java.lang.String UNIT) {
		set("UNIT", UNIT);
		return (M)this;
	}
	
	public java.lang.String getUNIT() {
		return getStr("UNIT");
	}

	public M setDisplaySeq(java.lang.Integer displaySeq) {
		set("DISPLAY_SEQ", displaySeq);
		return (M)this;
	}
	
	public java.lang.Integer getDisplaySeq() {
		return getInt("DISPLAY_SEQ");
	}

	public M setENABLED(java.lang.Integer ENABLED) {
		set("ENABLED", ENABLED);
		return (M)this;
	}
	
	public java.lang.Integer getENABLED() {
		return getInt("ENABLED");
	}

	public M setVERSION(java.lang.Integer VERSION) {
		set("VERSION", VERSION);
		return (M)this;
	}
	
	public java.lang.Integer getVERSION() {
		return getInt("VERSION");
	}

	public M setSTATUS(java.lang.Integer STATUS) {
		set("STATUS", STATUS);
		return (M)this;
	}
	
	public java.lang.Integer getSTATUS() {
		return getInt("STATUS");
	}

	public M setREMARK(java.lang.String REMARK) {
		set("REMARK", REMARK);
		return (M)this;
	}
	
	public java.lang.String getREMARK() {
		return getStr("REMARK");
	}

	public M setCreateBy(java.lang.String createBy) {
		set("CREATE_BY", createBy);
		return (M)this;
	}
	
	public java.lang.String getCreateBy() {
		return getStr("CREATE_BY");
	}

	public M setCreateDt(java.lang.String createDt) {
		set("CREATE_DT", createDt);
		return (M)this;
	}
	
	public java.lang.String getCreateDt() {
		return getStr("CREATE_DT");
	}

	public M setUpdateDt(java.lang.String updateDt) {
		set("UPDATE_DT", updateDt);
		return (M)this;
	}
	
	public java.lang.String getUpdateDt() {
		return getStr("UPDATE_DT");
	}

}
