package com.ns.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BasePntCategories<M extends BasePntCategories<M>> extends Model<M> implements IBean {

	public M setID(java.lang.String ID) {
		set("ID", ID);
		return (M)this;
	}
	
	public java.lang.String getID() {
		return getStr("ID");
	}

	public M setCategoryName(java.lang.String categoryName) {
		set("CATEGORY_NAME", categoryName);
		return (M)this;
	}
	
	public java.lang.String getCategoryName() {
		return getStr("CATEGORY_NAME");
	}

	public M setCategoryCode(java.lang.String categoryCode) {
		set("CATEGORY_CODE", categoryCode);
		return (M)this;
	}
	
	public java.lang.String getCategoryCode() {
		return getStr("CATEGORY_CODE");
	}

	public M setCategoryDesc(java.lang.String categoryDesc) {
		set("CATEGORY_DESC", categoryDesc);
		return (M)this;
	}
	
	public java.lang.String getCategoryDesc() {
		return getStr("CATEGORY_DESC");
	}

	public M setLinkUrl(java.lang.String linkUrl) {
		set("LINK_URL", linkUrl);
		return (M)this;
	}
	
	public java.lang.String getLinkUrl() {
		return getStr("LINK_URL");
	}

	public M setIconUrl(java.lang.String iconUrl) {
		set("ICON_URL", iconUrl);
		return (M)this;
	}
	
	public java.lang.String getIconUrl() {
		return getStr("ICON_URL");
	}

	public M setDisplaySeq(java.lang.Integer displaySeq) {
		set("DISPLAY_SEQ", displaySeq);
		return (M)this;
	}
	
	public java.lang.Integer getDisplaySeq() {
		return getInt("DISPLAY_SEQ");
	}

	public M setENABLED(java.lang.Integer ENABLED) {
		set("ENABLED", ENABLED);
		return (M)this;
	}
	
	public java.lang.Integer getENABLED() {
		return getInt("ENABLED");
	}

	public M setVERSION(java.lang.Integer VERSION) {
		set("VERSION", VERSION);
		return (M)this;
	}
	
	public java.lang.Integer getVERSION() {
		return getInt("VERSION");
	}

	public M setSTATUS(java.lang.Integer STATUS) {
		set("STATUS", STATUS);
		return (M)this;
	}
	
	public java.lang.Integer getSTATUS() {
		return getInt("STATUS");
	}

	public M setREMARK(java.lang.String REMARK) {
		set("REMARK", REMARK);
		return (M)this;
	}
	
	public java.lang.String getREMARK() {
		return getStr("REMARK");
	}

	public M setCreateBy(java.lang.String createBy) {
		set("CREATE_BY", createBy);
		return (M)this;
	}
	
	public java.lang.String getCreateBy() {
		return getStr("CREATE_BY");
	}

	public M setCreateDt(java.lang.String createDt) {
		set("CREATE_DT", createDt);
		return (M)this;
	}
	
	public java.lang.String getCreateDt() {
		return getStr("CREATE_DT");
	}

	public M setUpdateDt(java.lang.String updateDt) {
		set("UPDATE_DT", updateDt);
		return (M)this;
	}
	
	public java.lang.String getUpdateDt() {
		return getStr("UPDATE_DT");
	}

}
