package com.ns.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BasePntProductCmt<M extends BasePntProductCmt<M>> extends Model<M> implements IBean {

	public M setID(java.lang.String ID) {
		set("ID", ID);
		return (M)this;
	}
	
	public java.lang.String getID() {
		return getStr("ID");
	}

	public M setParentId(java.lang.String parentId) {
		set("PARENT_ID", parentId);
		return (M)this;
	}
	
	public java.lang.String getParentId() {
		return getStr("PARENT_ID");
	}

	public M setSourceId(java.lang.String sourceId) {
		set("SOURCE_ID", sourceId);
		return (M)this;
	}
	
	public java.lang.String getSourceId() {
		return getStr("SOURCE_ID");
	}

	public M setPntName(java.lang.String pntName) {
		set("PNT_NAME", pntName);
		return (M)this;
	}
	
	public java.lang.String getPntName() {
		return getStr("PNT_NAME");
	}

	public M setConId(java.lang.String conId) {
		set("CON_ID", conId);
		return (M)this;
	}
	
	public java.lang.String getConId() {
		return getStr("CON_ID");
	}

	public M setConNo(java.lang.String conNo) {
		set("CON_NO", conNo);
		return (M)this;
	}
	
	public java.lang.String getConNo() {
		return getStr("CON_NO");
	}

	public M setConName(java.lang.String conName) {
		set("CON_NAME", conName);
		return (M)this;
	}
	
	public java.lang.String getConName() {
		return getStr("CON_NAME");
	}

	public M setPIC(java.lang.String PIC) {
		set("PIC", PIC);
		return (M)this;
	}
	
	public java.lang.String getPIC() {
		return getStr("PIC");
	}

	public M setPhotoUrl1(java.lang.String photoUrl1) {
		set("PHOTO_URL1", photoUrl1);
		return (M)this;
	}
	
	public java.lang.String getPhotoUrl1() {
		return getStr("PHOTO_URL1");
	}

	public M setCONTENT(java.lang.String CONTENT) {
		set("CONTENT", CONTENT);
		return (M)this;
	}
	
	public java.lang.String getCONTENT() {
		return getStr("CONTENT");
	}

	public M setPhotoUrl2(java.lang.String photoUrl2) {
		set("PHOTO_URL2", photoUrl2);
		return (M)this;
	}
	
	public java.lang.String getPhotoUrl2() {
		return getStr("PHOTO_URL2");
	}

	public M setLikeQty(java.lang.Integer likeQty) {
		set("LIKE_QTY", likeQty);
		return (M)this;
	}
	
	public java.lang.Integer getLikeQty() {
		return getInt("LIKE_QTY");
	}

	public M setToConId(java.lang.String toConId) {
		set("TO_CON_ID", toConId);
		return (M)this;
	}
	
	public java.lang.String getToConId() {
		return getStr("TO_CON_ID");
	}

	public M setToConNo(java.lang.String toConNo) {
		set("TO_CON_NO", toConNo);
		return (M)this;
	}
	
	public java.lang.String getToConNo() {
		return getStr("TO_CON_NO");
	}

	public M setToConName(java.lang.String toConName) {
		set("TO_CON_NAME", toConName);
		return (M)this;
	}
	
	public java.lang.String getToConName() {
		return getStr("TO_CON_NAME");
	}

	public M setENABLED(java.lang.Integer ENABLED) {
		set("ENABLED", ENABLED);
		return (M)this;
	}
	
	public java.lang.Integer getENABLED() {
		return getInt("ENABLED");
	}

	public M setVERSION(java.lang.Integer VERSION) {
		set("VERSION", VERSION);
		return (M)this;
	}
	
	public java.lang.Integer getVERSION() {
		return getInt("VERSION");
	}

	public M setSTATUS(java.lang.Integer STATUS) {
		set("STATUS", STATUS);
		return (M)this;
	}
	
	public java.lang.Integer getSTATUS() {
		return getInt("STATUS");
	}

	public M setREMARK(java.lang.String REMARK) {
		set("REMARK", REMARK);
		return (M)this;
	}
	
	public java.lang.String getREMARK() {
		return getStr("REMARK");
	}

	public M setCreateBy(java.lang.String createBy) {
		set("CREATE_BY", createBy);
		return (M)this;
	}
	
	public java.lang.String getCreateBy() {
		return getStr("CREATE_BY");
	}

	public M setCreateDt(java.lang.String createDt) {
		set("CREATE_DT", createDt);
		return (M)this;
	}
	
	public java.lang.String getCreateDt() {
		return getStr("CREATE_DT");
	}

	public M setUpdateDt(java.lang.String updateDt) {
		set("UPDATE_DT", updateDt);
		return (M)this;
	}
	
	public java.lang.String getUpdateDt() {
		return getStr("UPDATE_DT");
	}

	public M setPhotoUrl3(java.lang.String photoUrl3) {
		set("PHOTO_URL3", photoUrl3);
		return (M)this;
	}
	
	public java.lang.String getPhotoUrl3() {
		return getStr("PHOTO_URL3");
	}

}
