package com.ns.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseBasCustAddress<M extends BaseBasCustAddress<M>> extends Model<M> implements IBean {

	public M setID(java.lang.String ID) {
		set("ID", ID);
		return (M)this;
	}
	
	public java.lang.String getID() {
		return getStr("ID");
	}

	public M setConId(java.lang.String conId) {
		set("CON_ID", conId);
		return (M)this;
	}
	
	public java.lang.String getConId() {
		return getStr("CON_ID");
	}

	public M setTEL(java.lang.String TEL) {
		set("TEL", TEL);
		return (M)this;
	}
	
	public java.lang.String getTEL() {
		return getStr("TEL");
	}

	public M setIsDefault(java.lang.Integer isDefault) {
		set("IS_DEFAULT", isDefault);
		return (M)this;
	}
	
	public java.lang.Integer getIsDefault() {
		return getInt("IS_DEFAULT");
	}

	public M setMOBILE(java.lang.String MOBILE) {
		set("MOBILE", MOBILE);
		return (M)this;
	}
	
	public java.lang.String getMOBILE() {
		return getStr("MOBILE");
	}

	public M setRECIPIENTS(java.lang.String RECIPIENTS) {
		set("RECIPIENTS", RECIPIENTS);
		return (M)this;
	}
	
	public java.lang.String getRECIPIENTS() {
		return getStr("RECIPIENTS");
	}

	public M setPostalCode(java.lang.String postalCode) {
		set("POSTAL_CODE", postalCode);
		return (M)this;
	}
	
	public java.lang.String getPostalCode() {
		return getStr("POSTAL_CODE");
	}

	public M setENABLED(java.lang.Integer ENABLED) {
		set("ENABLED", ENABLED);
		return (M)this;
	}
	
	public java.lang.Integer getENABLED() {
		return getInt("ENABLED");
	}

	public M setVERSION(java.lang.Integer VERSION) {
		set("VERSION", VERSION);
		return (M)this;
	}
	
	public java.lang.Integer getVERSION() {
		return getInt("VERSION");
	}

	public M setSTATUS(java.lang.Integer STATUS) {
		set("STATUS", STATUS);
		return (M)this;
	}
	
	public java.lang.Integer getSTATUS() {
		return getInt("STATUS");
	}

	public M setREMARK(java.lang.String REMARK) {
		set("REMARK", REMARK);
		return (M)this;
	}
	
	public java.lang.String getREMARK() {
		return getStr("REMARK");
	}

	public M setCreateBy(java.lang.String createBy) {
		set("CREATE_BY", createBy);
		return (M)this;
	}
	
	public java.lang.String getCreateBy() {
		return getStr("CREATE_BY");
	}

	public M setCreateDt(java.lang.String createDt) {
		set("CREATE_DT", createDt);
		return (M)this;
	}
	
	public java.lang.String getCreateDt() {
		return getStr("CREATE_DT");
	}

	public M setUpdateDt(java.lang.String updateDt) {
		set("UPDATE_DT", updateDt);
		return (M)this;
	}
	
	public java.lang.String getUpdateDt() {
		return getStr("UPDATE_DT");
	}

	public M setCOUNTRY(java.lang.String COUNTRY) {
		set("COUNTRY", COUNTRY);
		return (M)this;
	}
	
	public java.lang.String getCOUNTRY() {
		return getStr("COUNTRY");
	}

	public M setPROVINCE(java.lang.String PROVINCE) {
		set("PROVINCE", PROVINCE);
		return (M)this;
	}
	
	public java.lang.String getPROVINCE() {
		return getStr("PROVINCE");
	}

	public M setCITY(java.lang.String CITY) {
		set("CITY", CITY);
		return (M)this;
	}
	
	public java.lang.String getCITY() {
		return getStr("CITY");
	}

	public M setDISTRICT(java.lang.String DISTRICT) {
		set("DISTRICT", DISTRICT);
		return (M)this;
	}
	
	public java.lang.String getDISTRICT() {
		return getStr("DISTRICT");
	}

	public M setADDRESS(java.lang.String ADDRESS) {
		set("ADDRESS", ADDRESS);
		return (M)this;
	}
	
	public java.lang.String getADDRESS() {
		return getStr("ADDRESS");
	}

}
