package com.ns.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTldOrders<M extends BaseTldOrders<M>> extends Model<M> implements IBean {

	public M setID(java.lang.String ID) {
		set("ID", ID);
		return (M)this;
	}
	
	public java.lang.String getID() {
		return getStr("ID");
	}

	public M setOrderNo(java.lang.String orderNo) {
		set("ORDER_NO", orderNo);
		return (M)this;
	}
	
	public java.lang.String getOrderNo() {
		return getStr("ORDER_NO");
	}

	public M setConId(java.lang.String conId) {
		set("CON_ID", conId);
		return (M)this;
	}
	
	public java.lang.String getConId() {
		return getStr("CON_ID");
	}

	public M setConNo(java.lang.String conNo) {
		set("CON_NO", conNo);
		return (M)this;
	}
	
	public java.lang.String getConNo() {
		return getStr("CON_NO");
	}

	public M setConName(java.lang.String conName) {
		set("CON_NAME", conName);
		return (M)this;
	}
	
	public java.lang.String getConName() {
		return getStr("CON_NAME");
	}

	public M setPIC(java.lang.String PIC) {
		set("PIC", PIC);
		return (M)this;
	}
	
	public java.lang.String getPIC() {
		return getStr("PIC");
	}

	public M setCouponGrantId(java.lang.String couponGrantId) {
		set("COUPON_GRANT_ID", couponGrantId);
		return (M)this;
	}
	
	public java.lang.String getCouponGrantId() {
		return getStr("COUPON_GRANT_ID");
	}

	public M setPayDt(java.lang.String payDt) {
		set("PAY_DT", payDt);
		return (M)this;
	}
	
	public java.lang.String getPayDt() {
		return getStr("PAY_DT");
	}

	public M setShippingDt(java.lang.String shippingDt) {
		set("SHIPPING_DT", shippingDt);
		return (M)this;
	}
	
	public java.lang.String getShippingDt() {
		return getStr("SHIPPING_DT");
	}

	public M setConfirmDt(java.lang.String confirmDt) {
		set("CONFIRM_DT", confirmDt);
		return (M)this;
	}
	
	public java.lang.String getConfirmDt() {
		return getStr("CONFIRM_DT");
	}

	public M setCOUNTRY(java.lang.String COUNTRY) {
		set("COUNTRY", COUNTRY);
		return (M)this;
	}
	
	public java.lang.String getCOUNTRY() {
		return getStr("COUNTRY");
	}

	public M setPROVINCE(java.lang.String PROVINCE) {
		set("PROVINCE", PROVINCE);
		return (M)this;
	}
	
	public java.lang.String getPROVINCE() {
		return getStr("PROVINCE");
	}

	public M setCITY(java.lang.String CITY) {
		set("CITY", CITY);
		return (M)this;
	}
	
	public java.lang.String getCITY() {
		return getStr("CITY");
	}

	public M setDISTRICT(java.lang.String DISTRICT) {
		set("DISTRICT", DISTRICT);
		return (M)this;
	}
	
	public java.lang.String getDISTRICT() {
		return getStr("DISTRICT");
	}

	public M setADDRESS(java.lang.String ADDRESS) {
		set("ADDRESS", ADDRESS);
		return (M)this;
	}
	
	public java.lang.String getADDRESS() {
		return getStr("ADDRESS");
	}

	public M setPostalCode(java.lang.String postalCode) {
		set("POSTAL_CODE", postalCode);
		return (M)this;
	}
	
	public java.lang.String getPostalCode() {
		return getStr("POSTAL_CODE");
	}

	public M setMOBILE(java.lang.String MOBILE) {
		set("MOBILE", MOBILE);
		return (M)this;
	}
	
	public java.lang.String getMOBILE() {
		return getStr("MOBILE");
	}

	public M setRECIPIENTS(java.lang.String RECIPIENTS) {
		set("RECIPIENTS", RECIPIENTS);
		return (M)this;
	}
	
	public java.lang.String getRECIPIENTS() {
		return getStr("RECIPIENTS");
	}

	public M setFREIGHT(java.math.BigDecimal FREIGHT) {
		set("FREIGHT", FREIGHT);
		return (M)this;
	}
	
	public java.math.BigDecimal getFREIGHT() {
		return get("FREIGHT");
	}

	public M setWEIGHT(java.math.BigDecimal WEIGHT) {
		set("WEIGHT", WEIGHT);
		return (M)this;
	}
	
	public java.math.BigDecimal getWEIGHT() {
		return get("WEIGHT");
	}

	public M setPaymentTypeid(java.lang.String paymentTypeid) {
		set("PAYMENT_TYPEID", paymentTypeid);
		return (M)this;
	}
	
	public java.lang.String getPaymentTypeid() {
		return getStr("PAYMENT_TYPEID");
	}

	public M setPaymentType(java.lang.String paymentType) {
		set("PAYMENT_TYPE", paymentType);
		return (M)this;
	}
	
	public java.lang.String getPaymentType() {
		return getStr("PAYMENT_TYPE");
	}

	public M setOrderSource(java.lang.Integer orderSource) {
		set("ORDER_SOURCE", orderSource);
		return (M)this;
	}
	
	public java.lang.Integer getOrderSource() {
		return getInt("ORDER_SOURCE");
	}

	public M setOrderType(java.lang.Integer orderType) {
		set("ORDER_TYPE", orderType);
		return (M)this;
	}
	
	public java.lang.Integer getOrderType() {
		return getInt("ORDER_TYPE");
	}

	public M setOrderTotal(java.math.BigDecimal orderTotal) {
		set("ORDER_TOTAL", orderTotal);
		return (M)this;
	}
	
	public java.math.BigDecimal getOrderTotal() {
		return get("ORDER_TOTAL");
	}

	public M setCouponAmount(java.math.BigDecimal couponAmount) {
		set("COUPON_AMOUNT", couponAmount);
		return (M)this;
	}
	
	public java.math.BigDecimal getCouponAmount() {
		return get("COUPON_AMOUNT");
	}

	public M setIntegralAmount(java.math.BigDecimal integralAmount) {
		set("INTEGRAL_AMOUNT", integralAmount);
		return (M)this;
	}
	
	public java.math.BigDecimal getIntegralAmount() {
		return get("INTEGRAL_AMOUNT");
	}

	public M setPntAmount(java.math.BigDecimal pntAmount) {
		set("PNT_AMOUNT", pntAmount);
		return (M)this;
	}
	
	public java.math.BigDecimal getPntAmount() {
		return get("PNT_AMOUNT");
	}

	public M setIsDiscount(java.lang.Integer isDiscount) {
		set("IS_DISCOUNT", isDiscount);
		return (M)this;
	}
	
	public java.lang.Integer getIsDiscount() {
		return getInt("IS_DISCOUNT");
	}

	public M setIsReorder(java.lang.Integer isReorder) {
		set("IS_REORDER", isReorder);
		return (M)this;
	}
	
	public java.lang.Integer getIsReorder() {
		return getInt("IS_REORDER");
	}

	public M setSelfIntegral(java.lang.Integer selfIntegral) {
		set("SELF_INTEGRAL", selfIntegral);
		return (M)this;
	}
	
	public java.lang.Integer getSelfIntegral() {
		return getInt("SELF_INTEGRAL");
	}

	public M setUp1Integral(java.lang.Integer up1Integral) {
		set("UP1_INTEGRAL", up1Integral);
		return (M)this;
	}
	
	public java.lang.Integer getUp1Integral() {
		return getInt("UP1_INTEGRAL");
	}

	public M setRpId(java.lang.String rpId) {
		set("RP_ID", rpId);
		return (M)this;
	}
	
	public java.lang.String getRpId() {
		return getStr("RP_ID");
	}

	public M setRpNo(java.lang.String rpNo) {
		set("RP_NO", rpNo);
		return (M)this;
	}
	
	public java.lang.String getRpNo() {
		return getStr("RP_NO");
	}

	public M setRpName(java.lang.String rpName) {
		set("RP_NAME", rpName);
		return (M)this;
	}
	
	public java.lang.String getRpName() {
		return getStr("RP_NAME");
	}

	public M setENABLED(java.lang.Integer ENABLED) {
		set("ENABLED", ENABLED);
		return (M)this;
	}
	
	public java.lang.Integer getENABLED() {
		return getInt("ENABLED");
	}

	public M setVERSION(java.lang.Integer VERSION) {
		set("VERSION", VERSION);
		return (M)this;
	}
	
	public java.lang.Integer getVERSION() {
		return getInt("VERSION");
	}

	public M setSTATUS(java.lang.Integer STATUS) {
		set("STATUS", STATUS);
		return (M)this;
	}
	
	public java.lang.Integer getSTATUS() {
		return getInt("STATUS");
	}

	public M setREMARK(java.lang.String REMARK) {
		set("REMARK", REMARK);
		return (M)this;
	}
	
	public java.lang.String getREMARK() {
		return getStr("REMARK");
	}

	public M setCreateBy(java.lang.String createBy) {
		set("CREATE_BY", createBy);
		return (M)this;
	}
	
	public java.lang.String getCreateBy() {
		return getStr("CREATE_BY");
	}

	public M setCreateDt(java.lang.String createDt) {
		set("CREATE_DT", createDt);
		return (M)this;
	}
	
	public java.lang.String getCreateDt() {
		return getStr("CREATE_DT");
	}

	public M setUpdateDt(java.lang.String updateDt) {
		set("UPDATE_DT", updateDt);
		return (M)this;
	}
	
	public java.lang.String getUpdateDt() {
		return getStr("UPDATE_DT");
	}

}
