package com.ns.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseNodeCmt<M extends BaseNodeCmt<M>> extends Model<M> implements IBean {

	public M setID(java.lang.String ID) {
		set("ID", ID);
		return (M)this;
	}
	
	public java.lang.String getID() {
		return getStr("ID");
	}

	public M setParentId(java.lang.String parentId) {
		set("PARENT_ID", parentId);
		return (M)this;
	}
	
	public java.lang.String getParentId() {
		return getStr("PARENT_ID");
	}

	public M setSourceId(java.lang.String sourceId) {
		set("SOURCE_ID", sourceId);
		return (M)this;
	}
	
	public java.lang.String getSourceId() {
		return getStr("SOURCE_ID");
	}

	public M setConId(java.lang.String conId) {
		set("CON_ID", conId);
		return (M)this;
	}
	
	public java.lang.String getConId() {
		return getStr("CON_ID");
	}

	public M setConNo(java.lang.String conNo) {
		set("CON_NO", conNo);
		return (M)this;
	}
	
	public java.lang.String getConNo() {
		return getStr("CON_NO");
	}

	public M setConName(java.lang.String conName) {
		set("CON_NAME", conName);
		return (M)this;
	}
	
	public java.lang.String getConName() {
		return getStr("CON_NAME");
	}

	public M setConPic(java.lang.String conPic) {
		set("CON_PIC", conPic);
		return (M)this;
	}
	
	public java.lang.String getConPic() {
		return getStr("CON_PIC");
	}

	public M setCONTENT(java.lang.String CONTENT) {
		set("CONTENT", CONTENT);
		return (M)this;
	}
	
	public java.lang.String getCONTENT() {
		return getStr("CONTENT");
	}

	public M setToConId(java.lang.String toConId) {
		set("TO_CON_ID", toConId);
		return (M)this;
	}
	
	public java.lang.String getToConId() {
		return getStr("TO_CON_ID");
	}

	public M setToConNo(java.lang.String toConNo) {
		set("TO_CON_NO", toConNo);
		return (M)this;
	}
	
	public java.lang.String getToConNo() {
		return getStr("TO_CON_NO");
	}

	public M setToConName(java.lang.String toConName) {
		set("TO_CON_NAME", toConName);
		return (M)this;
	}
	
	public java.lang.String getToConName() {
		return getStr("TO_CON_NAME");
	}

	public M setToConPic(java.lang.String toConPic) {
		set("TO_CON_PIC", toConPic);
		return (M)this;
	}
	
	public java.lang.String getToConPic() {
		return getStr("TO_CON_PIC");
	}

	public M setByConId(java.lang.String byConId) {
		set("BY_CON_ID", byConId);
		return (M)this;
	}
	
	public java.lang.String getByConId() {
		return getStr("BY_CON_ID");
	}

	public M setENABLED(java.lang.Integer ENABLED) {
		set("ENABLED", ENABLED);
		return (M)this;
	}
	
	public java.lang.Integer getENABLED() {
		return getInt("ENABLED");
	}

	public M setVERSION(java.lang.Integer VERSION) {
		set("VERSION", VERSION);
		return (M)this;
	}
	
	public java.lang.Integer getVERSION() {
		return getInt("VERSION");
	}

	public M setSTATUS(java.lang.Integer STATUS) {
		set("STATUS", STATUS);
		return (M)this;
	}
	
	public java.lang.Integer getSTATUS() {
		return getInt("STATUS");
	}

	public M setREMARK(java.lang.String REMARK) {
		set("REMARK", REMARK);
		return (M)this;
	}
	
	public java.lang.String getREMARK() {
		return getStr("REMARK");
	}

	public M setCreateBy(java.lang.String createBy) {
		set("CREATE_BY", createBy);
		return (M)this;
	}
	
	public java.lang.String getCreateBy() {
		return getStr("CREATE_BY");
	}

	public M setCreateDt(java.lang.String createDt) {
		set("CREATE_DT", createDt);
		return (M)this;
	}
	
	public java.lang.String getCreateDt() {
		return getStr("CREATE_DT");
	}

	public M setUpdateDt(java.lang.String updateDt) {
		set("UPDATE_DT", updateDt);
		return (M)this;
	}
	
	public java.lang.String getUpdateDt() {
		return getStr("UPDATE_DT");
	}

}
