package com.ns.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTldQrbgmParams<M extends BaseTldQrbgmParams<M>> extends Model<M> implements IBean {

	public M setID(java.lang.String ID) {
		set("ID", ID);
		return (M)this;
	}
	
	public java.lang.String getID() {
		return getStr("ID");
	}

	public M setQrX(java.lang.Integer qrX) {
		set("QR_X", qrX);
		return (M)this;
	}
	
	public java.lang.Integer getQrX() {
		return getInt("QR_X");
	}

	public M setQrY(java.lang.Integer qrY) {
		set("QR_Y", qrY);
		return (M)this;
	}
	
	public java.lang.Integer getQrY() {
		return getInt("QR_Y");
	}

	public M setQrW(java.lang.Integer qrW) {
		set("QR_W", qrW);
		return (M)this;
	}
	
	public java.lang.Integer getQrW() {
		return getInt("QR_W");
	}

	public M setQrH(java.lang.Integer qrH) {
		set("QR_H", qrH);
		return (M)this;
	}
	
	public java.lang.Integer getQrH() {
		return getInt("QR_H");
	}

	public M setIconX(java.lang.Integer iconX) {
		set("ICON_X", iconX);
		return (M)this;
	}
	
	public java.lang.Integer getIconX() {
		return getInt("ICON_X");
	}

	public M setIconY(java.lang.Integer iconY) {
		set("ICON_Y", iconY);
		return (M)this;
	}
	
	public java.lang.Integer getIconY() {
		return getInt("ICON_Y");
	}

	public M setIconW(java.lang.Integer iconW) {
		set("ICON_W", iconW);
		return (M)this;
	}
	
	public java.lang.Integer getIconW() {
		return getInt("ICON_W");
	}

	public M setIconH(java.lang.Integer iconH) {
		set("ICON_H", iconH);
		return (M)this;
	}
	
	public java.lang.Integer getIconH() {
		return getInt("ICON_H");
	}

	public M setCodeUrl(java.lang.String codeUrl) {
		set("CODE_URL", codeUrl);
		return (M)this;
	}
	
	public java.lang.String getCodeUrl() {
		return getStr("CODE_URL");
	}

	public M setFontCharset(java.lang.String fontCharset) {
		set("FONT_CHARSET", fontCharset);
		return (M)this;
	}
	
	public java.lang.String getFontCharset() {
		return getStr("FONT_CHARSET");
	}

	public M setFontSize(java.lang.Integer fontSize) {
		set("FONT_SIZE", fontSize);
		return (M)this;
	}
	
	public java.lang.Integer getFontSize() {
		return getInt("FONT_SIZE");
	}

	public M setConNameX(java.lang.Integer conNameX) {
		set("CON_NAME_X", conNameX);
		return (M)this;
	}
	
	public java.lang.Integer getConNameX() {
		return getInt("CON_NAME_X");
	}

	public M setConNameY(java.lang.Integer conNameY) {
		set("CON_NAME_Y", conNameY);
		return (M)this;
	}
	
	public java.lang.Integer getConNameY() {
		return getInt("CON_NAME_Y");
	}

	public M setShowConName(java.lang.Integer showConName) {
		set("SHOW_CON_NAME", showConName);
		return (M)this;
	}
	
	public java.lang.Integer getShowConName() {
		return getInt("SHOW_CON_NAME");
	}

	public M setShowIcon(java.lang.Integer showIcon) {
		set("SHOW_ICON", showIcon);
		return (M)this;
	}
	
	public java.lang.Integer getShowIcon() {
		return getInt("SHOW_ICON");
	}

	public M setENABLED(java.lang.Integer ENABLED) {
		set("ENABLED", ENABLED);
		return (M)this;
	}
	
	public java.lang.Integer getENABLED() {
		return getInt("ENABLED");
	}

	public M setVERSION(java.lang.Integer VERSION) {
		set("VERSION", VERSION);
		return (M)this;
	}
	
	public java.lang.Integer getVERSION() {
		return getInt("VERSION");
	}

	public M setSTATUS(java.lang.Integer STATUS) {
		set("STATUS", STATUS);
		return (M)this;
	}
	
	public java.lang.Integer getSTATUS() {
		return getInt("STATUS");
	}

	public M setREMARK(java.lang.String REMARK) {
		set("REMARK", REMARK);
		return (M)this;
	}
	
	public java.lang.String getREMARK() {
		return getStr("REMARK");
	}

	public M setCreateBy(java.lang.String createBy) {
		set("CREATE_BY", createBy);
		return (M)this;
	}
	
	public java.lang.String getCreateBy() {
		return getStr("CREATE_BY");
	}

	public M setCreateDt(java.lang.String createDt) {
		set("CREATE_DT", createDt);
		return (M)this;
	}
	
	public java.lang.String getCreateDt() {
		return getStr("CREATE_DT");
	}

	public M setUpdateDt(java.lang.String updateDt) {
		set("UPDATE_DT", updateDt);
		return (M)this;
	}
	
	public java.lang.String getUpdateDt() {
		return getStr("UPDATE_DT");
	}

}
