package com.ns.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseBasCustomerRequest<M extends BaseBasCustomerRequest<M>> extends Model<M> implements IBean {

	public M setID(java.lang.String ID) {
		set("ID", ID);
		return (M)this;
	}
	
	public java.lang.String getID() {
		return getStr("ID");
	}

	public M setConId(java.lang.String conId) {
		set("CON_ID", conId);
		return (M)this;
	}
	
	public java.lang.String getConId() {
		return getStr("CON_ID");
	}

	public M setConNo(java.lang.String conNo) {
		set("CON_NO", conNo);
		return (M)this;
	}
	
	public java.lang.String getConNo() {
		return getStr("CON_NO");
	}

	public M setConName(java.lang.String conName) {
		set("CON_NAME", conName);
		return (M)this;
	}
	
	public java.lang.String getConName() {
		return getStr("CON_NAME");
	}

	public M setOrderId(java.lang.String orderId) {
		set("ORDER_ID", orderId);
		return (M)this;
	}
	
	public java.lang.String getOrderId() {
		return getStr("ORDER_ID");
	}

	public M setOrderNo(java.lang.String orderNo) {
		set("ORDER_NO", orderNo);
		return (M)this;
	}
	
	public java.lang.String getOrderNo() {
		return getStr("ORDER_NO");
	}

	public M setRequestType(java.lang.Integer requestType) {
		set("REQUEST_TYPE", requestType);
		return (M)this;
	}
	
	public java.lang.Integer getRequestType() {
		return getInt("REQUEST_TYPE");
	}

	public M setRequestStatus(java.lang.Integer requestStatus) {
		set("REQUEST_STATUS", requestStatus);
		return (M)this;
	}
	
	public java.lang.Integer getRequestStatus() {
		return getInt("REQUEST_STATUS");
	}

	public M setRefundType(java.lang.Integer refundType) {
		set("REFUND_TYPE", refundType);
		return (M)this;
	}
	
	public java.lang.Integer getRefundType() {
		return getInt("REFUND_TYPE");
	}

	public M setAMOUNT(java.math.BigDecimal AMOUNT) {
		set("AMOUNT", AMOUNT);
		return (M)this;
	}
	
	public java.math.BigDecimal getAMOUNT() {
		return get("AMOUNT");
	}

	public M setCustServiceChecktime(java.lang.String custServiceChecktime) {
		set("CUST_SERVICE_CHECKTIME", custServiceChecktime);
		return (M)this;
	}
	
	public java.lang.String getCustServiceChecktime() {
		return getStr("CUST_SERVICE_CHECKTIME");
	}

	public M setCustServiceCheckresult(java.lang.Integer custServiceCheckresult) {
		set("CUST_SERVICE_CHECKRESULT", custServiceCheckresult);
		return (M)this;
	}
	
	public java.lang.Integer getCustServiceCheckresult() {
		return getInt("CUST_SERVICE_CHECKRESULT");
	}

	public M setCustServiceCheckRemark(java.lang.String custServiceCheckRemark) {
		set("CUST_SERVICE_CHECK_REMARK", custServiceCheckRemark);
		return (M)this;
	}
	
	public java.lang.String getCustServiceCheckRemark() {
		return getStr("CUST_SERVICE_CHECK_REMARK");
	}

	public M setFinCheckDt(java.lang.String finCheckDt) {
		set("FIN_CHECK_DT", finCheckDt);
		return (M)this;
	}
	
	public java.lang.String getFinCheckDt() {
		return getStr("FIN_CHECK_DT");
	}

	public M setFinCheckResult(java.lang.Integer finCheckResult) {
		set("FIN_CHECK_RESULT", finCheckResult);
		return (M)this;
	}
	
	public java.lang.Integer getFinCheckResult() {
		return getInt("FIN_CHECK_RESULT");
	}

	public M setFinCheckRemark(java.lang.String finCheckRemark) {
		set("FIN_CHECK_REMARK", finCheckRemark);
		return (M)this;
	}
	
	public java.lang.String getFinCheckRemark() {
		return getStr("FIN_CHECK_REMARK");
	}

	public M setReturnReason(java.lang.Integer returnReason) {
		set("RETURN_REASON", returnReason);
		return (M)this;
	}
	
	public java.lang.Integer getReturnReason() {
		return getInt("RETURN_REASON");
	}

	public M setPntPhotoUrl1(java.lang.String pntPhotoUrl1) {
		set("PNT_PHOTO_URL1", pntPhotoUrl1);
		return (M)this;
	}
	
	public java.lang.String getPntPhotoUrl1() {
		return getStr("PNT_PHOTO_URL1");
	}

	public M setPntPhotoUrl2(java.lang.String pntPhotoUrl2) {
		set("PNT_PHOTO_URL2", pntPhotoUrl2);
		return (M)this;
	}
	
	public java.lang.String getPntPhotoUrl2() {
		return getStr("PNT_PHOTO_URL2");
	}

	public M setPntPhotoUrl3(java.lang.String pntPhotoUrl3) {
		set("PNT_PHOTO_URL3", pntPhotoUrl3);
		return (M)this;
	}
	
	public java.lang.String getPntPhotoUrl3() {
		return getStr("PNT_PHOTO_URL3");
	}

	public M setExpCompanyId(java.lang.String expCompanyId) {
		set("EXP_COMPANY_ID", expCompanyId);
		return (M)this;
	}
	
	public java.lang.String getExpCompanyId() {
		return getStr("EXP_COMPANY_ID");
	}

	public M setExpWaybill(java.lang.String expWaybill) {
		set("EXP_WAYBILL", expWaybill);
		return (M)this;
	}
	
	public java.lang.String getExpWaybill() {
		return getStr("EXP_WAYBILL");
	}

	public M setIsReturn(java.lang.Integer isReturn) {
		set("IS_RETURN", isReturn);
		return (M)this;
	}
	
	public java.lang.Integer getIsReturn() {
		return getInt("IS_RETURN");
	}

	public M setRefundStatus(java.lang.Integer refundStatus) {
		set("REFUND_STATUS", refundStatus);
		return (M)this;
	}
	
	public java.lang.Integer getRefundStatus() {
		return getInt("REFUND_STATUS");
	}

	public M setRefundTransfer(java.lang.Integer refundTransfer) {
		set("REFUND_TRANSFER", refundTransfer);
		return (M)this;
	}
	
	public java.lang.Integer getRefundTransfer() {
		return getInt("REFUND_TRANSFER");
	}

	public M setENABLED(java.lang.Integer ENABLED) {
		set("ENABLED", ENABLED);
		return (M)this;
	}
	
	public java.lang.Integer getENABLED() {
		return getInt("ENABLED");
	}

	public M setVERSION(java.lang.Integer VERSION) {
		set("VERSION", VERSION);
		return (M)this;
	}
	
	public java.lang.Integer getVERSION() {
		return getInt("VERSION");
	}

	public M setSTATUS(java.lang.Integer STATUS) {
		set("STATUS", STATUS);
		return (M)this;
	}
	
	public java.lang.Integer getSTATUS() {
		return getInt("STATUS");
	}

	public M setREMARK(java.lang.String REMARK) {
		set("REMARK", REMARK);
		return (M)this;
	}
	
	public java.lang.String getREMARK() {
		return getStr("REMARK");
	}

	public M setCreateBy(java.lang.String createBy) {
		set("CREATE_BY", createBy);
		return (M)this;
	}
	
	public java.lang.String getCreateBy() {
		return getStr("CREATE_BY");
	}

	public M setCreateDt(java.lang.String createDt) {
		set("CREATE_DT", createDt);
		return (M)this;
	}
	
	public java.lang.String getCreateDt() {
		return getStr("CREATE_DT");
	}

	public M setUpdateDt(java.lang.String updateDt) {
		set("UPDATE_DT", updateDt);
		return (M)this;
	}
	
	public java.lang.String getUpdateDt() {
		return getStr("UPDATE_DT");
	}

}
