package com.ns.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BasePntMenu<M extends BasePntMenu<M>> extends Model<M> implements IBean {

	public M setID(java.lang.String ID) {
		set("ID", ID);
		return (M)this;
	}
	
	public java.lang.String getID() {
		return getStr("ID");
	}

	public M setMenuName(java.lang.String menuName) {
		set("MENU_NAME", menuName);
		return (M)this;
	}
	
	public java.lang.String getMenuName() {
		return getStr("MENU_NAME");
	}

	public M setMenuDesc(java.lang.String menuDesc) {
		set("MENU_DESC", menuDesc);
		return (M)this;
	}
	
	public java.lang.String getMenuDesc() {
		return getStr("MENU_DESC");
	}

	public M setMenuType(java.lang.Integer menuType) {
		set("MENU_TYPE", menuType);
		return (M)this;
	}
	
	public java.lang.Integer getMenuType() {
		return getInt("MENU_TYPE");
	}

	public M setMenuValue(java.lang.String menuValue) {
		set("MENU_VALUE", menuValue);
		return (M)this;
	}
	
	public java.lang.String getMenuValue() {
		return getStr("MENU_VALUE");
	}

	public M setIconUrl(java.lang.String iconUrl) {
		set("ICON_URL", iconUrl);
		return (M)this;
	}
	
	public java.lang.String getIconUrl() {
		return getStr("ICON_URL");
	}

	public M setDisplaySeq(java.lang.Integer displaySeq) {
		set("DISPLAY_SEQ", displaySeq);
		return (M)this;
	}
	
	public java.lang.Integer getDisplaySeq() {
		return getInt("DISPLAY_SEQ");
	}

	public M setENABLED(java.lang.Integer ENABLED) {
		set("ENABLED", ENABLED);
		return (M)this;
	}
	
	public java.lang.Integer getENABLED() {
		return getInt("ENABLED");
	}

	public M setVERSION(java.lang.Integer VERSION) {
		set("VERSION", VERSION);
		return (M)this;
	}
	
	public java.lang.Integer getVERSION() {
		return getInt("VERSION");
	}

	public M setSTATUS(java.lang.Integer STATUS) {
		set("STATUS", STATUS);
		return (M)this;
	}
	
	public java.lang.Integer getSTATUS() {
		return getInt("STATUS");
	}

	public M setREMARK(java.lang.String REMARK) {
		set("REMARK", REMARK);
		return (M)this;
	}
	
	public java.lang.String getREMARK() {
		return getStr("REMARK");
	}

	public M setCreateBy(java.lang.String createBy) {
		set("CREATE_BY", createBy);
		return (M)this;
	}
	
	public java.lang.String getCreateBy() {
		return getStr("CREATE_BY");
	}

	public M setCreateDt(java.lang.String createDt) {
		set("CREATE_DT", createDt);
		return (M)this;
	}
	
	public java.lang.String getCreateDt() {
		return getStr("CREATE_DT");
	}

	public M setUpdateDt(java.lang.String updateDt) {
		set("UPDATE_DT", updateDt);
		return (M)this;
	}
	
	public java.lang.String getUpdateDt() {
		return getStr("UPDATE_DT");
	}

}
