package com.ns.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseBasCustomer<M extends BaseBasCustomer<M>> extends Model<M> implements IBean {

	public M setID(java.lang.String ID) {
		set("ID", ID);
		return (M)this;
	}
	
	public java.lang.String getID() {
		return getStr("ID");
	}

	public M setConNo(java.lang.String conNo) {
		set("CON_NO", conNo);
		return (M)this;
	}
	
	public java.lang.String getConNo() {
		return getStr("CON_NO");
	}

	public M setConName(java.lang.String conName) {
		set("CON_NAME", conName);
		return (M)this;
	}
	
	public java.lang.String getConName() {
		return getStr("CON_NAME");
	}

	public M setRealName(java.lang.String realName) {
		set("REAL_NAME", realName);
		return (M)this;
	}
	
	public java.lang.String getRealName() {
		return getStr("REAL_NAME");
	}

	public M setConType(java.lang.Integer conType) {
		set("CON_TYPE", conType);
		return (M)this;
	}
	
	public java.lang.Integer getConType() {
		return getInt("CON_TYPE");
	}

	public M setPIC(java.lang.String PIC) {
		set("PIC", PIC);
		return (M)this;
	}
	
	public java.lang.String getPIC() {
		return getStr("PIC");
	}

	public M setSEX(java.lang.Integer SEX) {
		set("SEX", SEX);
		return (M)this;
	}
	
	public java.lang.Integer getSEX() {
		return getInt("SEX");
	}

	public M setBIRTHDAY(java.lang.String BIRTHDAY) {
		set("BIRTHDAY", BIRTHDAY);
		return (M)this;
	}
	
	public java.lang.String getBIRTHDAY() {
		return getStr("BIRTHDAY");
	}

	public M setCOUNTRY(java.lang.String COUNTRY) {
		set("COUNTRY", COUNTRY);
		return (M)this;
	}
	
	public java.lang.String getCOUNTRY() {
		return getStr("COUNTRY");
	}

	public M setPROVINCE(java.lang.String PROVINCE) {
		set("PROVINCE", PROVINCE);
		return (M)this;
	}
	
	public java.lang.String getPROVINCE() {
		return getStr("PROVINCE");
	}

	public M setCITY(java.lang.String CITY) {
		set("CITY", CITY);
		return (M)this;
	}
	
	public java.lang.String getCITY() {
		return getStr("CITY");
	}

	public M setDISTRICT(java.lang.String DISTRICT) {
		set("DISTRICT", DISTRICT);
		return (M)this;
	}
	
	public java.lang.String getDISTRICT() {
		return getStr("DISTRICT");
	}

	public M setADDRESS(java.lang.String ADDRESS) {
		set("ADDRESS", ADDRESS);
		return (M)this;
	}
	
	public java.lang.String getADDRESS() {
		return getStr("ADDRESS");
	}

	public M setMOBILE(java.lang.String MOBILE) {
		set("MOBILE", MOBILE);
		return (M)this;
	}
	
	public java.lang.String getMOBILE() {
		return getStr("MOBILE");
	}

	public M setUnionId(java.lang.String unionId) {
		set("UNION_ID", unionId);
		return (M)this;
	}
	
	public java.lang.String getUnionId() {
		return getStr("UNION_ID");
	}

	public M setOPENID(java.lang.String OPENID) {
		set("OPENID", OPENID);
		return (M)this;
	}
	
	public java.lang.String getOPENID() {
		return getStr("OPENID");
	}

	public M setIsLockout(java.lang.Integer isLockout) {
		set("IS_LOCKOUT", isLockout);
		return (M)this;
	}
	
	public java.lang.Integer getIsLockout() {
		return getInt("IS_LOCKOUT");
	}

	public M setRpId(java.lang.String rpId) {
		set("RP_ID", rpId);
		return (M)this;
	}
	
	public java.lang.String getRpId() {
		return getStr("RP_ID");
	}

	public M setRpNo(java.lang.String rpNo) {
		set("RP_NO", rpNo);
		return (M)this;
	}
	
	public java.lang.String getRpNo() {
		return getStr("RP_NO");
	}

	public M setRpName(java.lang.String rpName) {
		set("RP_NAME", rpName);
		return (M)this;
	}
	
	public java.lang.String getRpName() {
		return getStr("RP_NAME");
	}

	public M setIsSubscribe(java.lang.Integer isSubscribe) {
		set("IS_SUBSCRIBE", isSubscribe);
		return (M)this;
	}
	
	public java.lang.Integer getIsSubscribe() {
		return getInt("IS_SUBSCRIBE");
	}

	public M setENABLED(java.lang.Integer ENABLED) {
		set("ENABLED", ENABLED);
		return (M)this;
	}
	
	public java.lang.Integer getENABLED() {
		return getInt("ENABLED");
	}

	public M setVERSION(java.lang.Integer VERSION) {
		set("VERSION", VERSION);
		return (M)this;
	}
	
	public java.lang.Integer getVERSION() {
		return getInt("VERSION");
	}

	public M setSTATUS(java.lang.Integer STATUS) {
		set("STATUS", STATUS);
		return (M)this;
	}
	
	public java.lang.Integer getSTATUS() {
		return getInt("STATUS");
	}

	public M setREMARK(java.lang.String REMARK) {
		set("REMARK", REMARK);
		return (M)this;
	}
	
	public java.lang.String getREMARK() {
		return getStr("REMARK");
	}

	public M setCreateBy(java.lang.String createBy) {
		set("CREATE_BY", createBy);
		return (M)this;
	}
	
	public java.lang.String getCreateBy() {
		return getStr("CREATE_BY");
	}

	public M setCreateDt(java.lang.String createDt) {
		set("CREATE_DT", createDt);
		return (M)this;
	}
	
	public java.lang.String getCreateDt() {
		return getStr("CREATE_DT");
	}

	public M setUpdateDt(java.lang.String updateDt) {
		set("UPDATE_DT", updateDt);
		return (M)this;
	}
	
	public java.lang.String getUpdateDt() {
		return getStr("UPDATE_DT");
	}

}
